### ISSUE TITLE
Linux Build

### ISSUE THREAD

**Issue by sagunkho** [horizonxyz/horizon#29]
Get the project running on Linux pref. Debian or Ubuntu. Same workflow format as https://github.com/horizonxyz/horizon/actions/runs/4971727114 (all working)

**Comment by sagunkho** [comment]
https://gitpay.me/#/task/664/linux-build

**Comment by sagunkho** [comment]
This is a bounty on BountySource - https://app.bountysource.com/issues/121170059-linux-build

**Comment by sam0hack** [comment]
Can you describe more?

**Comment by sagunkho** [comment]
@sam0hack Just get the project running on Linux. In the same workflow format -
Dependencies - Libraries - Tests - Tools - Servers

**Comment by ishaanbedi** [comment]
Hi @sagunkho !
I'd like to work on this issue. Can you please assign it to me?
Thanks!

**Comment by sagunkho** [comment]
@ishaanbedi Sure @ishaanbedi , I've assigned it to you. :) Good luck!

**Comment by its-joseph-230606** [comment]
**Is this issue solved?**
